"""
TIF Metadata Parser

Module handles extraction of metadata from ThermoScientific .tif image files
generated by Auto Slice & View (ASV) 5 software.

Each .tif image contains two metadata sources embedded in TIFF tags:
    - Tag 34682: MicroscopeMetadata stored as key=value pairs
      with trailing '=' characters on keys.
    - Tag 34683: ASVXMLMetadata stored as an XML string containing
      acquisition parameters, optics, stage settings, and custom sections.

The module also parses the ASV filename convention to extract the detector
name and slice index. Example filename:
    "Oxygen_April26_TLD-Custom_q1_x01_y01_s0001.tif"
    -> detector: "TLD-Custom", slice_index: 1

"""
import logging
import re
import xml.etree.ElementTree as ET
from pathlib import Path
from typing import Any
import tifffile


logger = logging.getLogger(__name__)


# The four trailing coordinate tokens are deterministic ASV anchors used by
# parse_filename to locate the detector token by position rather than by
# character class.
_COORD_TOKEN_PATTERN = re.compile(r"^[qxys]\d+$")
_SLICE_TOKEN_PATTERN = re.compile(r"^s(\d+)$")
_COORD_PREFIXES = ("q", "x", "y", "s")
_NUM_COORD_TOKENS = len(_COORD_PREFIXES)


# --- Public Functions ---

def extract_tif_metadata(tif_path: Path) -> dict:
    """
    Extract all metadata from a single .tif image file.

    Reads TIFF tags 34682 (MicroscopeMetadata) and 34683 (ASVXMLMetadata),
    and parses the filename for detector name and slice index.

    :param tif_path: Path to the .tif image file.
    :return: Dictionary containing the extracted metadata.
    """
    filename = tif_path.name
    detector, slice_index = parse_filename(filename)

    metadata = {
        "ImageName": filename,
        "FileNameDetector": detector,
        "FileNameSliceIndex": slice_index,
        "Metadata": {
            "MicroscopeMetadata": {},
            "ASVXMLMetadata": {}
        }
    }

    try:
        with tifffile.TiffFile(tif_path) as tif:
            page = tif.pages[0]
            tags = page.tags

            # Tag 34682: MicroscopeMetadata
            if 34682 in tags:
                _data = tags[34682].value
                if isinstance(_data, dict):
                    metadata["Metadata"]["MicroscopeMetadata"] = (
                        _clean_microscope_metadata_keys(_data)
                    )

            # Tag 34683: ASVXMLMetadata
            if 34683 in tags:
                xml_data = tags[34683].value
                if isinstance(xml_data, str) and xml_data.strip():
                    parsed_xml = _parse_xml_metadata(xml_data)
                    if parsed_xml:
                        # Unwrap the root "Metadata" key if present
                        metadata["Metadata"]["ASVXMLMetadata"] = (
                            parsed_xml.get("Metadata", parsed_xml)
                        )

    except Exception:
        logger.error(f"Error extracting metadata from {tif_path.name}", exc_info=True)
        metadata["Error"] = "Error extracting metadata"

    return metadata


def parse_filename(filename: str) -> tuple[str | None, int | None]:
    """
    Parse detector name and slice index from an ASV image filename.

    Expected filename structure:
        "<ActivityName>_<Detector>_q<N>_x<N>_y<N>_s<SliceIndex>.tif"
    Example:
        "Oxygen_April26_TLD-Custom_q1_x01_y01_s0001.tif"
        -> ("TLD-Custom", 1)

    The activity name may contain underscores (e.g. "Oxygen_April26").
    The detector is identified by position relative to the trailing
    coordinate block rather than by character class, so any hyphenated
    detector name from ASV is handled (e.g. TLD-SE, TLD-Custom, In-Lens).

    :param filename: The image filename string.
    :return: Tuple of (detector_name, slice_index). Either may be None
             if the filename does not match the expected ASV structure.
    """
    detector: str | None = None
    slice_index: int | None = None

    try:
        tokens = Path(filename).stem.split("_")

        # Need at least: <activity> _ <detector> _ q _ x _ y _ s
        if len(tokens) < _NUM_COORD_TOKENS + 2:
            logger.warning(
                f"Filename '{filename}' has too few tokens to match the "
                "expected ASV structure (_<detector>_q<N>_x<N>_y<N>_s<N>)."
            )
            return detector, slice_index

        coord_tokens = tokens[-_NUM_COORD_TOKENS:]
        valid_suffix = all(
            tok.startswith(prefix) and _COORD_TOKEN_PATTERN.match(tok)
            for tok, prefix in zip(coord_tokens, _COORD_PREFIXES)
        )
        if not valid_suffix:
            logger.warning(
                f"Filename '{filename}' does not match the expected ASV "
                "coordinate-suffix structure (_q<N>_x<N>_y<N>_s<N>)."
            )
            return detector, slice_index

        # Detector is the token immediately preceding the coordinate block.
        detector = tokens[-(_NUM_COORD_TOKENS + 1)]

        slice_match = _SLICE_TOKEN_PATTERN.match(coord_tokens[-1])
        if slice_match:
            slice_index = int(slice_match.group(1))

    except Exception:
        logger.warning(f"Error parsing filename '{filename}'", exc_info=True)

    return detector, slice_index


# --- Private Helper Functions ---

def _clean_microscope_metadata_keys(data: Any) -> Any:
    """
    Recursively remove trailing '=' characters from MicroscopeMetadata keys.

    ThermoFisher TIFF tag 34682 stores keys with trailing '=' characters
    (e.g., "EBeam=" instead of "EBeam"). This function strips them for
    cleaner downstream access.

    :param data: The metadata structure (dict, list, or primitive).
    :return: Cleaned metadata structure with '=' removed from dict keys.
    """
    if isinstance(data, dict):
        return {
            (key.rstrip('=') if isinstance(key, str) else key):
            _clean_microscope_metadata_keys(value)
            for key, value in data.items()
        }
    elif isinstance(data, list):
        return [_clean_microscope_metadata_keys(item) for item in data]
    return data


def _parse_xml_metadata(xml_string: str) -> dict | None:
    """
    Parse XML metadata string (TIFF tag 34683) into a nested dictionary.

    Handles XML conventions including:
    - Namespace prefixes in element tags.
    - Scoped duplicate child elements (e.g., detector sections with
      a 'scope' attribute).
    - Numeric type conversion for leaf text values.

    Falls back to key=value line parsing if XML parsing fails.

    :param xml_string: The raw XML string from tag 34683.
    :return: Parsed metadata dictionary, or None on failure.
    """
    try:
        root = ET.fromstring(xml_string)
        metadata = {}
        _extract_xml_element(root, metadata)
        return metadata

    except ET.ParseError:
        # Fallback: some images use key=value format instead of XML
        logger.debug("XML parsing failed, attempting key=value fallback.", exc_info=True)
        return _parse_key_value_metadata(xml_string)
    except Exception:
        logger.error("Error parsing XML metadata", exc_info=True)
        return None


def _extract_xml_element(element: ET.Element, parent_dict: dict):
    """
    Recursively extract an XML element and its children into a dictionary.

    Handles three cases:
    1. Leaf nodes (no children, no attributes): stored as converted text value.
    2. Leaf nodes with attributes: stored as attribute dict, with text under '_text'.
    3. Branch nodes (has children): recursively processed, with special handling
       for duplicate-tagged children that use 'scope' attributes.

    :param element: The XML element to extract.
    :param parent_dict: The parent dictionary to insert the element data into.
    """
    # Strip namespace prefix from tag
    tag = element.tag.split('}')[-1] if '}' in element.tag else element.tag
    text = element.text.strip() if element.text and element.text.strip() else None
    attrs = dict(element.attrib)
    children = list(element)

    if not children and not attrs:
        # Leaf node with text only
        if text:
            parent_dict[tag] = _convert_text_value(text)

    elif not children and attrs:
        # Leaf node with attributes
        parent_dict[tag] = attrs
        if text:
            parent_dict[tag]['_text'] = text

    else:
        # Branch node with children
        child_dict = {}
        if attrs:
            child_dict.update(attrs)
        if text:
            child_dict['_text'] = text

        # Identify duplicate child tags for special handling
        child_tags = [
            c.tag.split('}')[-1] if '}' in c.tag else c.tag
            for c in children
        ]
        duplicate_tags = {t for t in child_tags if child_tags.count(t) > 1}

        for child in children:
            child_tag = (
                child.tag.split('}')[-1] if '}' in child.tag else child.tag
            )

            if child_tag in duplicate_tags:
                existing = child_dict.get(child_tag)
                if 'scope' in child.attrib:
                    # Scoped duplicate: group under scope name
                    if not isinstance(existing, dict):
                        # Mixed scoped/non-scoped siblings: keep any
                        # non-scoped duplicates already collected under
                        # an '_items' key inside the scope dict.
                        child_dict[child_tag] = (
                            {'_items': existing}
                            if isinstance(existing, list) else {}
                        )
                    scope = child.attrib['scope']
                    scope_dict = {}
                    for grandchild in child:
                        _extract_xml_element(grandchild, scope_dict)
                    # Unwrap single-key scope dict if key matches scope name
                    if len(scope_dict) == 1 and scope in scope_dict:
                        child_dict[child_tag][scope] = scope_dict[scope]
                    else:
                        child_dict[child_tag][scope] = scope_dict
                else:
                    # Non-scoped duplicate: collect into a list
                    item_dict = {}
                    _extract_xml_element(child, item_dict)
                    item = item_dict.get(child_tag, {})
                    if isinstance(existing, dict):
                        # Mixed scoped/non-scoped siblings: scoped
                        # entries stay in the dict, non-scoped ones
                        # collect under '_items'.
                        existing.setdefault('_items', []).append(item)
                    else:
                        if child_tag not in child_dict:
                            child_dict[child_tag] = []
                        child_dict[child_tag].append(item)
            else:
                # Unique child tag: recurse normally
                _extract_xml_element(child, child_dict)

        parent_dict[tag] = child_dict


def _convert_text_value(text: str) -> int | float | str:
    """
    Convert a text string to int, float, or leave as str.

    :param text: The text value to convert.
    :return: Converted value.
    """
    try:
        if '.' in text or 'e' in text.lower():
            return float(text)
        return int(text)
    except ValueError:
        return text


def _parse_key_value_metadata(description: str) -> dict | None:
    """
    Fallback parser for metadata stored as key=value lines.

    Some images store metadata in tag 34683 as
    plain text lines in "key=value" format rather than XML.

    :param description: The raw text string from the TIFF tag.
    :return: Parsed metadata dictionary, or None if no data found.
    """
    try:
        metadata = {}
        for line in description.split('\n'):
            if '=' in line:
                key, value = line.split('=', 1)
                key = key.strip()
                value = value.strip()
                metadata[key] = _convert_text_value(value)
        return metadata if metadata else None

    except Exception:
        logger.error("Error in key=value metadata fallback parser", exc_info=True)
        return None